# name: CI/CD Pipeline

# on:
#   workflow_dispatch:
#   push:
#     paths:
#       - terraform/**
#     branches:
#       - '**'

# jobs:
#   wf:
#     uses: lerpz-com/github-actions/.github/workflows/terraform-pipeline.yml@main
#     secrets: inherit
